name: Publish Python package
# Rust crate is published in release workflow

on:
  release:
    types: [published]

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: publish
    permissions:
      id-token: write # to authenticate as Trusted Publisher to pypi.org
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-python@v6
      with:
        python-version: '3.x'
        cache: pip
    - uses: dtolnay/rust-toolchain@stable
    - uses: PyO3/maturin-action@v1
      with:
        command: build
        args: --sdist --release -i python3.8 -i python3.9 -i python3.10 -i python3.11
    - uses: pypa/gh-action-pypi-publish@release/v1
      with:
        packages-dir: target/wheels
