name: Publish
# Rust crate is published in release workflow

on:
  push:
    branches: [main]
  pull_request:
  release:
    types: [published]

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    name: Create release PR or publish GitHub release and Rust crate
    if: github.event_name == 'push' && github.ref_name == 'main'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
    - uses: actions/checkout@v5
    - uses: dtolnay/rust-toolchain@stable
    - uses: MarcoIeni/release-plz-action@v0.5
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_GITHUB }}
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
  build:
    name: Build Python wheels
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-python@v6
      with:
        python-version: '3.x'
        cache: pip
    - uses: dtolnay/rust-toolchain@stable
    - uses: PyO3/maturin-action@v1
      with:
        command: build
        args: --sdist --release
    - uses: actions/upload-artifact@v4
      with:
        name: wheels
        path: target/wheels
  publish:
    name: Publish package
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    environment: publish
    permissions:
      id-token: write # to authenticate as Trusted Publisher to pypi.org
    steps:
    - uses: actions/download-artifact@v5
      with:
        name: wheels
        path: dist
    - uses: pypa/gh-action-pypi-publish@release/v1
