name: CI

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  PYTEST_ADDOPTS: --color=yes

jobs:
  build_and_test:
    name: Build, check, and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-python@v6
      with:
        python-version: '3.x'
        cache: pip
    - uses: dtolnay/rust-toolchain@stable
      with:
        components: clippy, rustfmt
    - uses: taiki-e/install-action@v2
      with:
        tool: cargo-hack,just
    - uses: Swatinem/rust-cache@v2
    - run: just build
    - run: pip install .[test]
    - run: just check
    - run: just fmt --check
    - run: just test
  doc:
    name: Build docs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: actions/configure-pages@v5
    - uses: dtolnay/rust-toolchain@nightly
    - uses: taiki-e/install-action@v2
      with:
        tool: just
    - uses: Swatinem/rust-cache@v2
    - run: just doc
    - uses: actions/upload-artifact@v4
      with:
        name: wheels
        path: target/doc
  publish:
    name: Publish docs
    if: github.ref_name == 'main'
    needs: doc
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
    - uses: actions/download-artifact@v5
      with:
        name: wheels
        path: _site
    - uses: actions/upload-pages-artifact@v4
    - uses: actions/deploy-pages@v4
      id: deployment
